# Form implementation generated from reading ui file 'src/app/ui/ui/getInfo_form.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import src.app.icons

class GetNote_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=Dialog)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.titel_lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.titel_lineEdit.setObjectName("titel_lineEdit")
        self.verticalLayout.addWidget(self.titel_lineEdit)
        self.content_label = QtWidgets.QLabel(parent=Dialog)
        self.content_label.setObjectName("content_label")
        self.verticalLayout.addWidget(self.content_label)
        self.content_plainTextEdit = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.content_plainTextEdit.setObjectName("content_plainTextEdit")
        self.verticalLayout.addWidget(self.content_plainTextEdit)
        self.del_btn = QtWidgets.QPushButton(parent=Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/remove.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.del_btn.setIcon(icon)
        self.del_btn.setObjectName("del_btn")
        self.verticalLayout.addWidget(self.del_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Get Info"))
        self.title_label.setText(_translate("Dialog", "Title"))
        self.content_label.setText(_translate("Dialog", "Content"))
        self.del_btn.setText(_translate("Dialog", "Delete"))
