# Form implementation generated from reading ui file 'ui/ui/main_form.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import src.app.icons

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 440)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon-app.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.addNote_btn = QtWidgets.QPushButton(parent=self.main_widget)
        self.addNote_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addNote_btn.setIcon(icon1)
        self.addNote_btn.setIconSize(QtCore.QSize(24, 24))
        self.addNote_btn.setObjectName("addNote_btn")
        self.gridLayout.addWidget(self.addNote_btn, 0, 0, 1, 1)
        self.search_lineEdit = QtWidgets.QLineEdit(parent=self.main_widget)
        self.search_lineEdit.setMinimumSize(QtCore.QSize(30, 30))
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.search_lineEdit.setPlaceholderText("Search")
        self.gridLayout.addWidget(self.search_lineEdit, 0, 1, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.tableNotes_widget = QtWidgets.QTableWidget(parent=self.main_widget)
        self.tableNotes_widget.setObjectName("tableNotes_widget")
        self.tableNotes_widget.setColumnCount(3)
        self.tableNotes_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableNotes_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNotes_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNotes_widget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableNotes_widget, 1, 0, 1, 3)
        self.verticalLayout.addWidget(self.main_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Notes App"))
        self.addNote_btn.setText(_translate("MainWindow", "Add Note"))
        item = self.tableNotes_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableNotes_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Content"))
