# Form implementation generated from reading ui file 'ui/ui/newNote_form.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class AddNote_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=Dialog)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.lineEdit_title = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.verticalLayout.addWidget(self.lineEdit_title)
        self.content_label = QtWidgets.QLabel(parent=Dialog)
        self.content_label.setObjectName("content_label")
        self.verticalLayout.addWidget(self.content_label)
        self.textEdit_content = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.textEdit_content.setObjectName("textEdit_content")
        self.verticalLayout.addWidget(self.textEdit_content)
        self.save_btn = QtWidgets.QPushButton(parent=Dialog)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Note"))
        self.title_label.setText(_translate("Dialog", "Enter a name:"))
        self.content_label.setText(_translate("Dialog", "Enter content:"))
        self.save_btn.setText(_translate("Dialog", "Save"))
